---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-paam-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kubernetes-paam
  name: kubernetes-paam
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-paam
  template:
    metadata:
      labels:
        app: kubernetes-paam
    spec:
      containers:
        - name: kubernetes-paam
          image: kristofferahl/kubernetes-paam:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: PAAM_ONLY_FAILED_RESULTS
              value: "false"
          ports:
            - name: http-port
              containerPort: 8113
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-paam-service
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: kubernetes-paam
  ports:
  - port: 8113
    protocol: TCP
    targetPort: http-port
